# Generated by Django 4.2 on 2023-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('persons', models.IntegerField()),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
